### PR TITLE
Handling exit and SIGINT events.

### PR DESCRIPTION
**Pull request by jakeorr**
for #33

### CODE REVIEW

**Comment by marvinroger** [comment]
I can confirm the PR is working fine.

**Comment by chrisdhanaraj** [comment]
+1

**Comment by marvinroger** [comment]
@jakeorr when typing `rs` to manually restart, the underlying process is not exited, even with this PR. I think the issue is the same kind as the one this PR resolves. Without the gulp overhead, it works great. Can you take a look at it?

**Comment by jakeorr** [comment]
@marvinroger I'm not able to reproduce this. When I `rs`, I no longer see the original process.

**Pull request merged**
