### PR TITLE
Added support for forcing nodemon events

### LINKED ISSUE #50: How to emit event back to the child process?
Is there a chance I can emit something back to the child from a gulp task?

### PR DESCRIPTION
**Pull request by IOAyman**
This enables you to do something like:
```js
const stream = nodemon( { ... } )

stream
    .on('restart', 'cssmin')
    .on('crash', function (){
      console.error('Application has crashed!\n')
      stream.emit('restart', 2)  // restart the server in 2 seconds
    })
```

This fixes #50

### CODE REVIEW

**Comment by JacksonGariety** [comment]
Merged manually

**Comment by IOAyman** [comment]
@JacksonGariety Please push the new changes to NPM repositories.

**Comment by JacksonGariety** [comment]
@IOAyman Can we merge pluggable nodemon first?

**Comment by IOAyman** [comment]
@JacksonGariety Yes, sure :+1:

**Pull request closed without merging**
