### PR TITLE
Temporarily pin to nodemon 1.3.7

### PR DESCRIPTION
**Pull request by ericqweinstein**
Temporary fix for https://github.com/JacksonGariety/gulp-nodemon/issues/80.

### CODE REVIEW

**Comment by ericqweinstein** [comment]
My guess is the breaking change in nodemon occurred [here](https://github.com/remy/nodemon/commit/15751fe4327c455822d374f52752978591925841), but I haven't dug through yet. We may end up closing this PR in favor of a fix against nodemon itself, but this one will at least unblock people while we figure it out.

**Comment by ericqweinstein** [comment]
Yeah, it looks like the nodemon change I mentioned above is the problem. It looks like maybe the [conditional is inverted](https://github.com/remy/nodemon/commit/15751fe4327c455822d374f52752978591925841#diff-cebf50326ac9e24a94de78bad36e77e1L321); I'll open an issue with them an x-ref this one.

**Comment by JacksonGariety** [comment]
This is fixed in the latest nodemon, so this can be closed

**Comment by ericqweinstein** [comment]
Thanks!

**Pull request closed without merging**
