### PR TITLE
Update to Gulp4

### PR DESCRIPTION
**Pull request by rejas**
Hi, I saw an old PR (thx to @erulabs for that) that didnt got updated to the final gulp4 release. Took some inspiration from it and cleaned up the code a little. Comments welcome @JacksonGariety

### CODE REVIEW

**Comment by xtforgame** [comment]
Well done @rejas 

I just doing the same thing. the different part is that I put the cb function in the `start event`, like this way:

```js
var called = false;

gulp.task('test', gulp.series('lint', function gulp_nodemon (cb) {
  stream
    .on('start', function () {
      if (!called) {
        called = true;
        cb(); <===
      }
    })
```

But I think it makes no significant difference with calling the cb function instantly :)

**Comment by rifler** [comment]
waiting for this...

**Comment by rejas** [comment]
Hi @JacksonGariety since there is no activity from you, do you plan on maintaining this repo or can we somehow help you?

**Comment by erulabs** [comment]
PR looks good to me! Also would be willing to help maintain the repo if some help is needed

**Comment by rejas** [comment]
Closing this since https://github.com/JacksonGariety/gulp-nodemon/pull/151 got merged

**Pull request closed without merging**
